name = "mailbox-worker"
main = "src/index.js"
compatibility_date = "2025-05-27"

[vars]
POLY_RPC_URL = "https://polygon-rpc.com"

# === Durable Object binding (single table) ===
[durable_objects]
bindings = [
  { name = "MAILBOX", class_name = "Mailbox" },
  { name = "ROOM",    class_name = "Mailbox" }
]

# === Migration to create your DO class ===
[[migrations]]
tag = "v2"
new_sqlite_classes = ["Mailbox"]
